name: Build and Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run build script
      run: python build.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: /home/runner/work/filebrowser/filebrowser/filebrowser.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: .  # 下载到当前工作目录
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1  # 使用新版本的创建发布动作
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0-${{ github.run_number }}
        name: Release v1.0.0-${{ github.run_number }}
        draft: false
        prerelease: false
        files: filebrowser.tar.gz  # 直接指定要上传的文件
