name: Build Project
on:
  push:
    branches:
      - master # 可以修改为你想要触发此工作流的分支，比如 master 等
jobs:
  build:
    runs-on: ubuntu-latest # 可以选择不同的运行环境，如 windows-latest、macos-latest 等，这里以 Ubuntu 为例
    steps:
    - uses: actions/checkout@v3 # 检出仓库代码到运行环境中
    - name: Set up Python environment
      uses: actions/setup-python@v4 # 设置 Python 环境，可指定版本等，默认安装较新版本
      with:
        python-version: 3.9 # 根据 build.py 对 Python 版本的要求填写合适的版本号，如 3.8、3.9 等
    - name: Run build.py
      run: python build.py # 执行 build.py 文件
