name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run build script
      run: python build.py

    - name: List files for debug
      run: ls -al /home/runner/work/filebrowser/filebrowser

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: /home/runner/work/filebrowser/filebrowser/filebrowser.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact

    - name: List downloaded files for debug
      run: ls -al

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: filebrowser.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
